version: '3'
services:
  {{ docker_compose_service_name }}:
    image: {{ docker_image_grafana_name }} 
    ports:
      - "{{ host_grafana_port }}:{{ docker_image_grafana_port }}"
    volumes:
      - {{ docker_image_grafana_local_main_path }}:/var/lib/grafana
    container_name: {{ docker_image_grafana_alias_name }}
    networks:
      - greaconsulting
networks:
  greaconsulting:
    external: true
