version: '3'
services:
  prometheus:
    image: {{ docker_image_prometheus_name }} 
    ports:
      - "{{ host_prometheus_port }}:{{ docker_image_prometheus_port }}"
    volumes:
      - {{ docker_image_prometheus_local_main_path }}/{{ docker_image_prometheus_local_config_file }}:/etc/prometheus/prometheus.yml
      - {{ docker_image_prometheus_local_main_path }}/{{ docker_image_prometheus_local_data_path }}:/prometheus
      - {{ docker_image_prometheus_local_main_path }}/{{ docker_image_prometheus_local_alter_file }}:/etc/prometheus/alert.rules
    container_name: {{ docker_image_prometheus_alias_name }}
    networks:
      - greaconsulting
networks:
  greaconsulting:
    external: true


