global:
  scrape_interval: 15s
  external_labels:
    monitor: '1699 office'
scrape_configs:
  - job_name: 'prometheus' 
    scrape_interval: 5s    
    static_configs:        
      - targets: ['127.0.0.1:9090']
  - job_name: 'sprint-actuator'
    metrics_path: '/actuator/prometheus'
    file_sd_configs:
      - files: ['sd_config/logwire.yml']
  - job_name: 'node-exporter'
    file_sd_configs:
      - files: ['sd_config/node-exporter.yml']
        refresh_interval: 5s
  - job_name: 'docker'
    file_sd_configs:
      - files: ['sd_config/docker.yml']
        refresh_interval: 5s
rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

