---
# tasks file for elasticsearch---
- name: create folder
  file:  
    path: "{{ docker_image_elasticsearch_local_main_path }}/{{ item }}"
    state: directory
    mode: 0777
  with_items:
  - "{{ docker_image_elasticsearch_local_data_path }}"

- name: template copy
  template:
    src: docker-compose.yml
    dest: "{{ docker_image_elasticsearch_local_main_path }}/docker-compose.yml"
  tags: compose

- name: docker run 
  command: "chdir={{ docker_image_elasticsearch_local_main_path }} docker-compose up -d"
  tags: run

- name: folder privilege change
  file:
    path: "{{ docker_image_elasticsearch_local_main_path }}"
    state: directory
    mode: 0777
    owner: root
    recurse: yes


