---
# tasks file for prometheus
- name: create folder 
  file:
    path: "{{ docker_image_prometheus_local_main_path }}/{{ item }}"
    state: directory
    mode: 0777
  with_items:
  - sd_config
  - alert.rules
  - "{{ docker_image_prometheus_local_data_path }}"

- name: chmod folder main
  file:  
    path: "{{ docker_image_prometheus_local_main_path }}"
    state: directory
    mode: 0777
    recurse: yes

- name: template copy
  template:
    src: "{{ item }}"
    dest: "{{ docker_image_prometheus_local_main_path }}/{{ item }}"
  with_items:
  - docker-compose.yml
  - prometheus.yml
  - prometheus.yml.sample
  - alert.rules/node.rules
  - alert.rules/node.rules.sample
  - sd_config/docker.yml
  - sd_config/docker.yml.sample
  - sd_config/logwire.yml
  - sd_config/logwire.yml.sample
  - sd_config/node-exporter.yml
  - sd_config/node-exporter.yml.sample

- name: docker run 
  command: "chdir={{ docker_image_prometheus_local_main_path }} docker-compose up -d"
