---
# tasks file for rabbitmq
- name: create folder
  file:  
    path: "{{ docker_image_rabbitmq_local_main_path }}"
    state: directory
    mode: 0777

- name: template copy
  template:
    src: "{{ item }}"
    dest: "{{ docker_image_rabbitmq_local_main_path }}/{{ item }}"
  with_items:
  - docker-compose.yml
  - rabbitmq.config

- name: docker run 
  command: "chdir={{ docker_image_rabbitmq_local_main_path }} docker-compose up -d"
