global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1m
  receiver: webhook
  routes:
  - receiver: webhook
    group_wait: 10s

receivers:
- name: webhook
  webhook_configs:
  - send_resolved: true
    url: http://{{ dingtalk_ip }}:{{ dingtalk_port}}/dingtalk/webhook/send
