---
# tasks file for logstash---
- name: create folder
  file:  
    path: "{{ docker_image_logstash_local_main_path }}"
    state: directory

- name: template copy
  template:
    src: "{{ item }}"
    dest: "{{ docker_image_logstash_local_main_path }}/{{ item }}"
  with_items:
  - docker-compose.yml
  - logstash.conf
  - logstash.yml
  - pipelines.yml
  
- name: docker run 
  command: "chdir={{ docker_image_logstash_local_main_path }} docker-compose up -d"
  tags: run
